# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protocol/migrater/migrater.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'protocol/migrater/migrater.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n protocol/migrater/migrater.proto\x12\x08migrater\"g\n\x16\x43heckpointSavedRequest\x12\x1d\n\x15\x63heckpoint_local_path\x18\x01 \x01(\t\x12\x1b\n\x13\x63heckpoint_pfs_path\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\x01\"%\n\x17\x43heckpointSavedResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x32o\n\x0fMigraterService\x12\\\n\x15NotifyCheckpointSaved\x12 .migrater.CheckpointSavedRequest\x1a!.migrater.CheckpointSavedResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protocol.migrater.migrater_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHECKPOINTSAVEDREQUEST']._serialized_start=46
  _globals['_CHECKPOINTSAVEDREQUEST']._serialized_end=149
  _globals['_CHECKPOINTSAVEDRESPONSE']._serialized_start=151
  _globals['_CHECKPOINTSAVEDRESPONSE']._serialized_end=188
  _globals['_MIGRATERSERVICE']._serialized_start=190
  _globals['_MIGRATERSERVICE']._serialized_end=301
# @@protoc_insertion_point(module_scope)
