# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from src.protocol import cluster_pb2 as src_dot_protocol_dot_cluster__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in src/protocol/cluster_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MigraterServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.NotifyCheckpointSaved = channel.unary_unary(
                '/cluster.MigraterService/NotifyCheckpointSaved',
                request_serializer=src_dot_protocol_dot_cluster__pb2.CheckpointSavedRequest.SerializeToString,
                response_deserializer=src_dot_protocol_dot_cluster__pb2.CheckpointSavedResponse.FromString,
                _registered_method=True)


class MigraterServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def NotifyCheckpointSaved(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MigraterServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'NotifyCheckpointSaved': grpc.unary_unary_rpc_method_handler(
                    servicer.NotifyCheckpointSaved,
                    request_deserializer=src_dot_protocol_dot_cluster__pb2.CheckpointSavedRequest.FromString,
                    response_serializer=src_dot_protocol_dot_cluster__pb2.CheckpointSavedResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cluster.MigraterService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cluster.MigraterService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MigraterService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def NotifyCheckpointSaved(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cluster.MigraterService/NotifyCheckpointSaved',
            src_dot_protocol_dot_cluster__pb2.CheckpointSavedRequest.SerializeToString,
            src_dot_protocol_dot_cluster__pb2.CheckpointSavedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class OrchestratorServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Monitor = channel.stream_stream(
                '/cluster.OrchestratorService/Monitor',
                request_serializer=src_dot_protocol_dot_cluster__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=src_dot_protocol_dot_cluster__pb2.InstructionResponse.FromString,
                _registered_method=True)


class OrchestratorServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Monitor(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OrchestratorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Monitor': grpc.stream_stream_rpc_method_handler(
                    servicer.Monitor,
                    request_deserializer=src_dot_protocol_dot_cluster__pb2.HeartbeatRequest.FromString,
                    response_serializer=src_dot_protocol_dot_cluster__pb2.InstructionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cluster.OrchestratorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cluster.OrchestratorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class OrchestratorService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Monitor(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/cluster.OrchestratorService/Monitor',
            src_dot_protocol_dot_cluster__pb2.HeartbeatRequest.SerializeToString,
            src_dot_protocol_dot_cluster__pb2.InstructionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
