syntax = "proto3";

package cluster;

service MigraterService {
  rpc NotifyCheckpointSaved (CheckpointSavedRequest)
  returns (CheckpointSavedResponse);
}

service OrchestratorService {
  rpc Monitor (stream HeartbeatRequest)
  returns (stream InstructionResponse);
}

// MigraterService

message CheckpointSavedRequest {
  string checkpoint_local_path = 1;
  string checkpoint_pfs_path   = 2;
  double timestamp             = 3;
  int64  epoch                 = 4;
  int64  total_epochs          = 5;
}

message CheckpointSavedResponse {
  bool ok = 1;
}

// Transfer Progress (Token Bucket Metrics) used in HeatbeatRequest

message TransferProgress {
  double timestamp               = 1;

  uint64 bytes_copied            = 2;
  uint64 total_bytes             = 3;
  uint64 remaining_bytes         = 4;

  double interval_seconds        = 5;
  double interval_throughput_bps = 6;
  double average_throughput_bps  = 7;

  double configured_rate_bps     = 8;
  uint64 chunk_size_bytes        = 9;
}

// OrchestratorService

message HeartbeatRequest {
  string worker_id                   = 1;
  double checkpoint_size             = 2;
  bool is_migrating                  = 3;
  repeated TransferProgress progress = 4;
  int64 epoch                        = 5;
  int64 total_epochs                 = 6;
}

message InstructionResponse {
  enum Action {
    HOLD        = 0;
    START_FLUSH = 1;
    CHANGE_RATE = 2;
  }

  Action action         = 1;
  double rate_limit_bps = 2;
}
