# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protocol/cluster.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'protocol/cluster.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16protocol/cluster.proto\x12\x07\x63luster\"g\n\x16\x43heckpointSavedRequest\x12\x1d\n\x15\x63heckpoint_local_path\x18\x01 \x01(\t\x12\x1b\n\x13\x63heckpoint_pfs_path\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\x01\"%\n\x17\x43heckpointSavedResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\"V\n\x10HeartbeatRequest\x12\x11\n\tworker_id\x18\x01 \x01(\t\x12\x19\n\x11pending_data_size\x18\x02 \x01(\x01\x12\x14\n\x0cis_migrating\x18\x03 \x01(\x08\"\x98\x01\n\x13InstructionResponse\x12\x33\n\x06\x61\x63tion\x18\x01 \x01(\x0e\x32#.cluster.InstructionResponse.Action\x12\x16\n\x0erate_limit_bps\x18\x02 \x01(\x01\"4\n\x06\x41\x63tion\x12\x08\n\x04HOLD\x10\x00\x12\x0f\n\x0bSTART_FLUSH\x10\x01\x12\x0f\n\x0b\x43HANGE_RATE\x10\x02\x32m\n\x0fMigraterService\x12Z\n\x15NotifyCheckpointSaved\x12\x1f.cluster.CheckpointSavedRequest\x1a .cluster.CheckpointSavedResponse2]\n\x13OrchestratorService\x12\x46\n\x07Monitor\x12\x19.cluster.HeartbeatRequest\x1a\x1c.cluster.InstructionResponse(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protocol.cluster_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHECKPOINTSAVEDREQUEST']._serialized_start=35
  _globals['_CHECKPOINTSAVEDREQUEST']._serialized_end=138
  _globals['_CHECKPOINTSAVEDRESPONSE']._serialized_start=140
  _globals['_CHECKPOINTSAVEDRESPONSE']._serialized_end=177
  _globals['_HEARTBEATREQUEST']._serialized_start=179
  _globals['_HEARTBEATREQUEST']._serialized_end=265
  _globals['_INSTRUCTIONRESPONSE']._serialized_start=268
  _globals['_INSTRUCTIONRESPONSE']._serialized_end=420
  _globals['_INSTRUCTIONRESPONSE_ACTION']._serialized_start=368
  _globals['_INSTRUCTIONRESPONSE_ACTION']._serialized_end=420
  _globals['_MIGRATERSERVICE']._serialized_start=422
  _globals['_MIGRATERSERVICE']._serialized_end=531
  _globals['_ORCHESTRATORSERVICE']._serialized_start=533
  _globals['_ORCHESTRATORSERVICE']._serialized_end=626
# @@protoc_insertion_point(module_scope)
